### PR TITLE
ensure that the NMEA sentence length does not exceed 82 characters

### PR DESCRIPTION
**Pull request by M0r13n**
Closes https://github.com/M0r13n/pyais/issues/81

### CODE REVIEW

**Comment by M0r13n** [comment]
@Inrixia 

As you are the only one that I can ask for a review: Would you take a look at this? :laughing:

**Review by Inrixia — APPROVED** [review]
Looks fine

**Review by Inrixia — APPROVED** [review]
Re approving for checks. But yea this is a simple change with minimal scope since its on the encoding side

**Comment by Inrixia** [comment]
Ah its approving review with write access. Thats why its not clearing checks, ah well all yours @M0r13n

**Pull request merged**
