### PR TITLE
Expose stream close method and make udp-receiver socket optional reusable

### PR DESCRIPTION
**Pull request by mib1185**
This will expose the `self._fobj.close()` as `close()` method, so we can close the stream even without running in a context manager. Further the udp listener socket can be set to be reusable, which helps in case of a fast close and reopen (_reuse_) of the same listener socket - eq. when the application restarts.

### CODE REVIEW

**Comment by M0r13n** [comment]
Hi @mib1185, looks good to me. However, there was a missing import statement, which caused some tests to fail. I have fixed this issue, and the changes are now available in version 2.7.1.

**Comment by mib1185** [comment]
Hi @M0r13n 
yeah I already recognized my _fault_ (_see https://github.com/M0r13n/pyais/commit/59e223044de72bde5e0e412257043f8b0866e598#r145478945_) :see_no_evil: 
Thanks for reviewing and merging this :slightly_smiling_face:

**Comment by M0r13n** [comment]
Hey @mib1185,

There was another issue with your PR. It causes an import error on Windows because the socket option for reusable sockets isn't available on that platform. Due to this, I decided to partially revert your changes. You can still set the socket options after creating a streaming instance (the socket attribute is public). I also yanked the faulty release from PyPI.

**Comment by mib1185** [comment]
Hi @M0r13n 
thanks for informing me about this!
OK, than I'll try to set these options afterwards direct in the socket property 👍

**Pull request merged**
